easy_admin:
    design:
        assets:
            css:
                # ...
                - 'scss/admin.scss'

        brand_color: '#1976d2'

    entities:
        - App\Entity\User
        - App\Entity\CircusAct

    site_name: 'Wild Circus'

    user:
        display_name: true
        display_avatar: false
        name_property_path: 'fullName'
        avatar_property_path: 'gravatar'